### ISSUE TITLE
support.get_fundamentus retorna DataFrame vazio

### ISSUE THREAD

**Issue by aateg** [GrupoTuring/turingquant#34]
Estou passando uma lista com os tickers para a função, porém o dataframe retornado está vazio.

```python
>>> get_fundamentus('WEGE3')
>>> get_fundamentus(tickers) # tickers é uma lista com tickers
```

**Comment by anor4k** [comment]
como discutimos no grupo, o request tá retornando 403 e dá pra arrumar colocando um user-agent válido.

**Comment by aateg** [comment]
### RESOLVIDO

Alterei a função `turingquant.support.get_fundamentus` adicionando o user-agent abaixo:

```python
response = requests.get(
    url, 
    headers={
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0'
    })
```

**Comment by gvmossato** [comment]
Resolvido #45. Adicionado header a cada request.
