### ISSUE TITLE
support.get_fundamentus não retorna dados de Setor e Subsetor 

### ISSUE THREAD

**Issue by aateg** [GrupoTuring/turingquant#35]
Verifiquei que para alguns ativos, talvez todos, as colunas Setor e Subsetor do pandas.DataFrame apresentam os valores fixos: Dados Históricos e Acionistas, respectivamente, conforme pode-se observar abaixo.
![image](https://user-images.githubusercontent.com/30242403/102932805-bf8a9d80-447f-11eb-8060-61f6efbcdbbf.png)

**Comment by gvmossato** [comment]
Resolvido #45. As tabelas da página agora são lidas com Pandas.
