### ISSUE TITLE
support.get_fundamentus não trata valores negativos

### ISSUE THREAD

**Issue by aateg** [GrupoTuring/turingquant#36]
O tratamento de dados ao transformar a resposta do request em pandas.DataFrame não trata valores negativos.

Verifiquei esse problema analisando a empresa CEDO3, cujo valor LPA no site do fundamentus é -5,85 (último balanço processado: 30/09/2020), e a resposta da função é +5,85. 

![image](https://user-images.githubusercontent.com/30242403/102933897-ecd84b00-4481-11eb-8f1b-f866917640ee.png)

![image](https://user-images.githubusercontent.com/30242403/102933949-fa8dd080-4481-11eb-946c-002f462b4311.png)

**Comment by aateg** [comment]
Fiz alguns testes, e aparentemente, retirar a chamada do método `.replace('-', '0')` dos indicadores resolve o problema.

**Comment by lucas-leme** [comment]
> Fiz alguns testes, e aparentemente, retirar a chamada do método `.replace('-', '0')` dos indicadores resolve o problema.

vc comitou essas solução? Pode fechar a issue?

**Comment by gvmossato** [comment]
Resolvido #45. As tabelas da página agora são lidas com Pandas.
